### ISSUE TITLE
Crash related to MPSwizzler.m line 44 mp_swizzledMethod_2

### ISSUE THREAD

**Issue by clkr** [mixpanel/mixpanel-iphone#228]
We're continuously getting a crash related to MPSwizzler.m line 44 mp_swizzledMethod_2.

The crash log states it is related to -[PFQueryTableViewController tableView:cellForRowAtIndexPath:] where we are using Parse.com's ParseUI PFQueryTableViewController.

PFQueryTableViewController has a load more cell that removes itself from table view after load more operation is completed. I believe mp_swizzledMethod_2 tries to reach the address on memory block after it is removed. Can you please suggest a way to fix this crash?

**Comment by davidgoli** [comment]
Also getting this crash. :+1:

**Comment by mekjaer** [comment]
Same here :+1:

**Comment by clkr** [comment]
If you're not using A/B testing, adding DISABLE_MIXPANEL_AB_DESIGNER=1 in build settings seems to resolve the issue.

Below is the message I got from support:
>Thanks so much for getting in touch with us! This looks like an issue with the particular view controller you're using - if the PFQueryTableViewController has elements that are removed after view did load it's definitely possible that our SDK is trying to reach access things in memory that no longer exist. Do you use our A/B testing stack? If not, you can pass in DISABLE_MIXPANEL_AB_DESIGNER=1 to disable the entire thing - I think this might just fix the crash, but we'll need to test it to be sure.

>Pass that flag as a preprocessor macro for the Pods>Pods-Mixpanel target - take a look at this screenshot to see what I mean: https://www.evernote.com/shard/s349/sh/e8bb7dbf-5e2b-45c6-a7d1-016cbaa83e37/f1c132944f2ca4a1dd042e59b7bc910e

**Comment by DarthMike** [comment]
Also getting this crash. +1

**Comment by arittr** [comment]
hey @DarthMike @clkr does this issue still occur in v2.8.1?

**Comment by clkr** [comment]
We discontinued using Mixpanel because of the crashes.

**Comment by arittr** [comment]
@clkr i'm really sorry to hear that - was this all due to the Parse issue detailed here? let me know if there's anything i can do to help going forward - feel free to email me at drew[at]mixpanel.com if you ever have Mixpanel questions in the future

**Comment by clkr** [comment]
Thanks @arittr we actually started speaking to the support since this bug first occurred. Their suggestions didn't help with the crash. You can see my comment on April 28th on this thread. So we decided to remove Mixpanel.

**Comment by ArtemGoryunov** [comment]
Getting this crash again and again...
![screen shot 2015-06-29 at 21 45 07](https://cloud.githubusercontent.com/assets/725247/8415549/2693f138-1ea8-11e5-8a4b-c0fcc254906a.png)

**Comment by DarthMike** [comment]
@arittr We will update our app and submit to Apple in our next release cycle (~2weeks) so we will have feedback later

**Comment by arittr** [comment]
@DarthMike OK sounds good - please let me know how it goes
@ArtemGoryunov what SDK version are you using?

**Comment by ArtemGoryunov** [comment]
@arittr we are using 2.7.3

**Comment by arittr** [comment]
@ArtemGoryunov can you try updating to v2.8.1 to see if the issue persists?

**Comment by samgreen** [comment]
Closing this stale issue. Please re-open if you're still having this problem.

**Comment by DarthMike** [comment]
@samgreen @arittr  Still seeing this issue in stack traces of application using v2.8.1

**Comment by samgreen** [comment]
@DarthMike can you please share a couple of those stack traces?

**Comment by DarthMike** [comment]
Here's one of the traces:

Date/Time:       2015-07-21T22:46:43Z
OS Version:      iPhone OS 8.4 (12H143)
Report Version:  104

Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0x150c9bec8
Crashed Thread:  0

Thread 0 Crashed:
0   libobjc.A.dylib                      0x0000000197fb8174 objc_release + 20
1   Bumble                               0x000000010091a35c mp_swizzledMethod_2 (MPSwizzler.m:44)
2   UIKit                                0x000000018ad48250 -[UIView(Hierarchy) _postMovedFromSuperview:] + 480
3   UIKit                                0x000000018ad54044 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1788
4   Bumble                               0x00000001000bad04 -[MOXProfileCard setupPageControl] (MOXProfileCard.m:119)
5   Bumble                               0x00000001000ba44c -[MOXProfileCard awakeFromNib] (MOXProfileCard.m:55)
6   UIKit                                0x000000018b16c8f4 -[UINib instantiateWithOwner:options:] + 2048
7   UIKit                                0x000000018b16e53c -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 184
8   Bumble                               0x00000001000acdf4 -[MOXReusableXibView awakeAfterUsingCoder:] (MOXReusableXibView.m:39)
9   UIKit                                0x000000018b2375c4 UINibDecoderDecodeObjectForValue + 932
10  UIKit                                0x000000018b237204 -[UINibDecoder decodeObjectForKey:] + 340
11  UIKit                                0x000000018b16d0dc -[UIRuntimeConnection initWithCoder:] + 164
12  UIKit                                0x000000018b237548 UINibDecoderDecodeObjectForValue + 808
13  UIKit                                0x000000018b2374e8 UINibDecoderDecodeObjectForValue + 712
14  UIKit                                0x000000018b237204 -[UINibDecoder decodeObjectForKey:] + 340
15  UIKit                                0x000000018b16c53c -[UINib instantiateWithOwner:options:] + 1096
16  UIKit                                0x000000018b068318 -[UIViewController _loadViewFromNibNamed:bundle:] + 280
17  UIKit                                0x000000018ad4c9bc -[UIViewController loadViewIfRequired] + 84
18  UIKit                                0x000000018ad4c928 -[UIViewController view] + 28
19  Bumble                               0x00000001000faa94 -[MOXSettingsSegue perform] (MOXSettingsSegue.m:15)
20  Bumble                               0x00000001000cfeb4 -[MOXProfileContainerViewController viewDidLoad] (MOXProfileContainerViewController.m:22)
21  UIKit                                0x000000018ad4cc18 -[UIViewController loadViewIfRequired] + 688
22  UIKit                                0x000000018ad4c928 -[UIViewController view] + 28
23  Foundation                           0x00000001870ecdb4 -[NSObject(NSKeyValueCoding) valueForKey:] + 236
24  Foundation                           0x000000018714b070 -[NSArray(NSKeyValueCoding) valueForKey:] + 444
25  Foundation                           0x0000000187164940 -[NSArray(NSKeyValueCoding) valueForKeyPath:] + 460
26  Bumble                               0x00000001000de858 -[MOXPageMenuController addControllersFromDataSource] (MOXPageMenuController.m:98)
27  Bumble                               0x00000001000de348 -[MOXPageMenuController reloadPages] (MOXPageMenuController.m:57)
28  Bumble                               0x0000000100094f68 -[MOXPagedNavigationController reloadPages] (MOXPagedNavigationController.m:87)
29  Bumble                               0x0000000100094618 -[MOXPagedNavigationController viewDidLoad] (MOXPagedNavigationController.m:23)
30  UIKit                                0x000000018ad4cc18 -[UIViewController loadViewIfRequired] + 688
31  UIKit                                0x000000018ad4c928 -[UIViewController view] + 28
32  Bumble                               0x00000001000d48ec -[MOXRootViewController presentScreenGroup:] (MOXRootViewController.m:94)
33  Bumble                               0x00000001000888f8 -[MOXApplicationFlow showApplicationScreens] (MOXApplicationFlow.m:174)
34  Bumble                               0x0000000100087ed4 __42-[MOXApplicationFlow setupStartupListener]_block_invoke (MOXApplicationFlow.m:102)
35  Bumble                               0x00000001002580e4 -[BPNNetworkService startupResponseComplete:] (BPNNetworkService.m:506)
36  Bumble                               0x000000010025aebc -[BPNStartupMessageTracker gotResponse] (BPNStartupMessageTracker.m:50)
37  Bumble                               0x0000000100256d0c -[BPNNetworkService handleResponseMessageWithoutContext:withId:responsesCount:] (BPNNetworkService.m:392)
38  Bumble                               0x00000001002567a8 -[BPNNetworkService handleResponseMessage:withId:responsesCount:] (BPNNetworkService.m:367)
39  Bumble                               0x00000001002560dc -[BPNNetworkService connection:didReceiveResponse:forMessageId:ofTotalCount:] (BPNNetworkService.m:328)
40  Bumble                               0x0000000100253718 -[BPNMessagingConnection messageReader:didReceiveMessage:] (BPNMessagingConnection.m:127)
41  Bumble                               0x000000010025a0b4 -[BPNProtobufMessageReader processMessage:] (BPNProtobufMessageReader.m:121)
42  Bumble                               0x000000010025a490 -[BPNProtobufMessageReader processMessageV2:] (BPNProtobufMessageReader.m:145)
43  Bumble                               0x0000000100259d88 -[BPNProtobufMessageReader socket:didReadData:withTag:] (BPNProtobufMessageReader.m:100)
44  Bumble                               0x00000001001d1958 -[BCAsyncSocketAdapter onSocket:didReadData:withTag:] (BCAsyncSocketAdapter.m:131)
45  Bumble                               0x0000000100805260 -[AsyncSocket completeCurrentRead] (AsyncSocket.m:3784)
46  Bumble                               0x0000000100804fbc -[AsyncSocket doBytesAvailable] (AsyncSocket.m:3720)
47  Foundation                           0x00000001871c8180 __NSFireDelayedPerform + 420
48  CoreFoundation                       0x000000018628c12c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 24
49  CoreFoundation                       0x000000018628bddc __CFRunLoopDoTimer + 884
50  CoreFoundation                       0x0000000186289828 __CFRunLoopRun + 1368
51  CoreFoundation                       0x00000001861b52d4 CFRunLoopRunSpecific + 392
52  GraphicsServices                     0x000000018fc0b6fc GSEventRunModal + 164
53  UIKit                                0x000000018adb2f40 UIApplicationMain + 1484
54  Bumble                               0x00000001000691a0 main (main.m:13)
55  libdyld.dylib                        0x000000019864aa08 start + 0

Thread 1:
0   libsystem_kernel.dylib               0x0000000198748c24 kevent64 + 8
1   libdispatch.dylib                    0x000000019861f99c _dispatch_mgr_thread + 48

Thread 2:
0   libsystem_kernel.dylib               0x0000000198763c78 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x00000001987fcef0 start_wqthread + 0

Thread 3:
0   Bumble                               0x0000000100a2cf48 _GLOBAL__I_a + 3800
1   Bumble                               0x000000010091cd94 -[MPUIControlBinding stop] (MPUIControlBinding.m:168)
2   CoreFoundation                       0x0000000186235960 -[NSSet makeObjectsPerformSelector:] + 216
3   Bumble                               0x0000000100932c4c __58-[Mixpanel checkForDecideResponseWithCompletion:useCache:]_block_invoke (Mixpanel.m:1301)
4   libdispatch.dylib                    0x000000019861d994 _dispatch_call_block_and_release + 20
5   libdispatch.dylib                    0x000000019861d954 _dispatch_client_callout + 12
6   libdispatch.dylib                    0x00000001986280a4 _dispatch_queue_drain + 1444
7   libdispatch.dylib                    0x0000000198620a5c _dispatch_queue_invoke + 128
8   libdispatch.dylib                    0x000000019862a318 _dispatch_root_queue_drain + 716
9   libdispatch.dylib                    0x000000019862bc4c _dispatch_worker_thread3 + 104
10  libsystem_pthread.dylib              0x00000001987fd22c _pthread_wqthread + 812
11  libsystem_pthread.dylib              0x00000001987fcef0 start_wqthread + 0

**Comment by DarthMike** [comment]
Just in case it helps, that view is not in hierarchy at that moment (it crashes while doing work in awakeFromNib). The bit crashing is when adding view to hierarchy. Here is the code:

```objc
- (void)setupPageControl {
    self.pageControl = [[MOXPageControl alloc] init];
    self.pageControl.profileDotEnabled = self.embeddedProfileEnabled;
    self.pageControl.dotBorderColour = [UIColor whiteColor];
    self.pageControl.defaultIndicatorColor = [UIColor whiteColor];
    self.pageControl.profileIndicatorColor = [UIColor appAccentColor];
    self.pageControl.dotScale = 1.2f;
    self.pageControl.translatesAutoresizingMaskIntoConstraints = NO;
    self.pageControl.transform = CGAffineTransformMakeRotation((CGFloat)(M_PI / 2));
    self.pageControl.pageIndicatorTintColor = [UIColor clearColor];
    self.pageControl.userInteractionEnabled = NO;
    [self addSubview:self.pageControl];
    [self updatePageControl];
}
```

**Comment by spf2** [comment]
Here's a (probably related) trace from a crash with 0.8.2:

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x00000001954f80b4 objc_retain + 20
1  Quorum                         0x00000001001eec84 mp_swizzledMethod_2 (MPSwizzler.m:44)
2  UIKit                          0x0000000188288250 -[UIView(Hierarchy) _postMovedFromSuperview:] + 484
3  UIKit                          0x0000000188294044 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1792
4  UIKit                          0x000000018832cd94 -[UINavigationBar _setLeftViews:rightViews:] + 6680
5  UIKit                          0x00000001883287c0 -[UINavigationBar _pushNavigationItem:transition:] + 512
6  UIKit                          0x00000001883281cc __71-[UINavigationController pushViewController:transition:forceImmediate:]_block_invoke + 328
7  UIKit                          0x000000018831cdb4 -[UINavigationController pushViewController:transition:forceImmediate:] + 1788
8  UIKit                          0x000000018831c694 -[UINavigationController pushViewController:animated:] + 532
9  UIKit                          0x000000018837a004 -[UINavigationController initWithRootViewController:] + 148
10 Quorum                         0x000000010011bf2c function signature specialization <Arg[0] = Owned To Guaranteed> of Quorum.SlideOutRailsViewController.viewDidLoad (Quorum.SlideOutRailsViewController)() -> () (SlideOutRailsViewController.swift:41)
11 Quorum                         0x0000000100119b90 @objc Quorum.SlideOutRailsViewController.viewDidLoad (Quorum.SlideOutRailsViewController)() -> () (SlideOutRailsViewController.swift)
12 UIKit                          0x000000018828cc18 -[UIViewController loadViewIfRequired] + 692
13 UIKit                          0x000000018828c928 -[UIViewController view] + 32
14 UIKit                          0x0000000188293164 -[UIWindow addRootViewControllerViewIfPossible] + 72
15 UIKit                          0x0000000188301358 -[UIWindow setRootViewController:] + 964
16 Quorum                         0x00000001000bd628 function signature specialization <Arg[0] = Owned To Guaranteed> of Quorum.AppDelegate.(updateRootVCForLoginState in _08EAEECF249999EA9FA1AD678DA85069) (Quorum.AppDelegate)() -> () (AppDelegate.swift:99)
17 Quorum                         0x00000001000bd210 function signature specialization <Arg[0] = Owned To Guaranteed> of Quorum.AppDelegate.stateChanged (Quorum.AppDelegate)() -> () (AppDelegate.swift:69)
18 Quorum                         0x00000001000bb358 Quorum.AppDelegate.stateChanged (Quorum.AppDelegate)() -> () (AppDelegate.swift)
19 Quorum                         0x0000000100132fa0 @objc Quorum.WaitForMeViewController.userUpdated (Quorum.WaitForMeViewController)(Swift.Optional<ObjectiveC.NSNotification>) -> () (WaitForMeViewController.swift:32)
20 CoreFoundation                 0x00000001837ba2c4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
21 CoreFoundation                 0x00000001836f7450 _CFXNotificationPost + 2060
22 Foundation                     0x00000001846852ec postQueueNotifications + 748
23 CoreFoundation                 0x00000001837cc2a4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
24 CoreFoundation                 0x00000001837c9230 __CFRunLoopDoObservers + 360
25 CoreFoundation                 0x00000001837c9560 __CFRunLoopRun + 660
26 CoreFoundation                 0x00000001836f52d4 CFRunLoopRunSpecific + 396
27 GraphicsServices               0x000000018d14b6fc GSEventRunModal + 168
28 UIKit                          0x00000001882f2f40 UIApplicationMain + 1488
29 Quorum                         0x00000001000bc5a0 main (AppDelegate.swift:15)
30 libdyld.dylib                  0x0000000195b8aa08 start + 4

**Comment by lucaseverini** [comment]
Hi everyone,
This issue is still well present and, I don't know what you think Mixpanel guys, is a serious one...
Removing the designer helped somewhat but the app still crashes sometime even if less often.
As a crash often means a lost user we need to solve this.
There are two possible choices, fix the problem or remove Mixpanel.
I prefer the former but I need some information to debug the problem myself.
First of all if I define mixpanel events only in code using [Mixpanel sharedIntance] track....., do I need all that method swizzling in MixPanel code?
I'm asking because I think if I can remove all of them, that's may fix the crash.

**Comment by falkobuttler** [comment]
This crash is the top crash in our crashlytics log and it is persistent across multiple versions of Mixpanel (currently on 2.8.1). We temporarily also compiled with DISABLE_MIXPANEL_AB_DESIGNER=1 but we actually rely on the dynamic events feature. But if this is not addressed soon, we will have to move away from Mixpanel as well.

**Comment by samgreen** [comment]
@falkobuttler If you can provide steps, or source to reproduce this, we would love to get it resolved. The reason is has been open since February is that we have been unable to reproduce the issue at all internally. The stack traces help, but if it's really difficult to know if we have resolved the issue when we cannot reliably reproduce it.

**Comment by lucaseverini** [comment]
I see is a bug quite difficult to reproduce.
What I can say is that since I removed all events defined from web UI the crash didn't happen again.
However looking at my crashlogs it seems something gets "confused" and invoke UI objects with methods registered in other objects. In my case a UIViewController method showCart: is called by a different object I never heard of in my code...

**Comment by falkobuttler** [comment]
@samgreen We don't have ways to reproduce it either but our customers encounter the crash often (top crash in our logs). It seems that Mixpanel tries to access views that we dynamically add/remove during runtime. Simply said you should always check the objects you access before making method calls on it, and method swizzling is very dangerous for exactly these reasons.

**Comment by lucaseverini** [comment]
I completely agree.
Swizzling is inherently (very) unsafe and should be the very last resort.
Did you explore all other possible ways?

**Comment by EvgenyKarkan** [comment]
Got such crashes too. In production =(

**Comment by ArtemGoryunov** [comment]
Again, again and again :-(
You can't fix it, but you can choose another approach (without swizzling)

<img width="974" alt="screen shot 2015-08-25 at 12 05 35" src="https://cloud.githubusercontent.com/assets/725247/9463039/862500be-4b22-11e5-9881-bbe7def333db.png">

**Comment by spf2** [comment]
Taking a quick look at the code, it doesn't appear to be an issue with swizzling per se, but with concurrent access and modifications to a singleton NSMapTable.  Did you consider making access to that NSMapTable thread safe?  It might be worth trying to see if it fixes these crashes, but maybe is not a bad idea anyway to be defensive even if you don't expect this class to be accessed by non-main-threads...

**Comment by samgreen** [comment]
Thanks @spf2. We'll take a look at that. 

Let's try and keep the comments in this thread as constructive as this one.

**Comment by samgreen** [comment]
I'm reviewing the NSMapTable access and writing more unit tests. Would really love any help or insight the community can provide. Thanks for all your help so far!

**Comment by A2K** [comment]
I have a quick fix for people who need to get it working right now. Simply replace mixpanel pod with 
`pod 'Mixpanel', :git => 'https://github.com/A2K/mixpanel-iphone.git'` and run `pod install`.
This will probably disable reporting of events created on website, so you'll need to send them from code like this: `Mixpanel.sharedInstance()?.track("MyEvent")`.

**Comment by samgreen** [comment]
Can you please pull request your changes? @A2K

**Comment by falkobuttler** [comment]
@samgreen I don't think a PR makes sense. He basically just hacked some code out of your library. It is literally a hack, not a real fix unless you plan to deprecate all of your dynamic event code.

**Comment by ItsTipTop** [comment]
Same here
Any fix?

**Comment by juliantejera** [comment]
Just had the dreaded crash too

**Comment by Artelas** [comment]
Version 2.9, the bug is still there :(

It happens in 
-(UIView*)tableView:(UITableView*)tableView viewForHeaderInSection:(NSInteger)section;

At line [sort_view2 addSubview:buttonMove];
Where sort_view2 is UIView and buttonMove is UIButton. Both declared in this method.


0 libobjc.A.dylib
objc_release + 7
1 App
MPSwizzler.m line 44
mp_swizzledMethod_2
2 UIKit	
__45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 502
3 UIKit	
-[UIView(Hierarchy) _postMovedFromSuperview:] + 426
4 UIKit	
-[UIView(Internal) _addSubview:positioned:relativeTo:] + 1608
5 UIKit	
-[UIView(Hierarchy) addSubview:] + 30
6 App
MyViewController.m line 1869
-[MyViewController tableView:viewForHeaderInSection:]

**Comment by okulak** [comment]
Version 2.8.1
Thread 0 Crashed:
0   libobjc.A.dylib                      0x00000001804b8160 objc_release + 16
1   Mixpanel                             0x00000001008635d4 mp_swizzledMethod_2 (MPSwizzler.m:44)
2   UIKit                                0x0000000185b1e4a4 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 552
3   UIKit                                0x0000000185b1e178 -[UIView(Hierarchy) _postMovedFromSuperview:] + 500
4   UIKit                                0x0000000185b2bb80 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1780
5   UIKit                                0x0000000185e28640 -[UIView initWithCoder:] + 716
6   UIKit                                0x000000018615f678 -[UITableViewCellContentView initWithCoder:] + 44
7   UIKit                                0x000000018610e67c UINibDecoderDecodeObjectForValue + 668
8   UIKit                                0x000000018610e7f4 UINibDecoderDecodeObjectForValue + 1044
9   UIKit                                0x000000018610e3c4 -[UINibDecoder decodeObjectForKey:] + 332
10  UIKit                                0x0000000185e285d0 -[UIView initWithCoder:] + 604
11  UIKit                                0x0000000185fc0630 -[UITableViewCell initWithCoder:] + 96

**Comment by wao813** [comment]
Still crash on 2.9.1, any news on this?

**Comment by sftnhrd** [comment]
So what about this problem? It's open about a year ago

**Comment by samgreen** [comment]
I think we *finally* have a fix for this. It will be in next release.

**Comment by SPopenko** [comment]
Hey @ArtemGoryunov what is the name of crash tracking system that you are using? It has interesting dashboard, exciting to check it also.

**Comment by ArtemGoryunov** [comment]
Hi @SPopenko
I'm using crashlytics from fabric.io

**Comment by SPopenko** [comment]
@ArtemGoryunov thanks!

**Comment by samgreen** [comment]
I am optimistically closing this issue as the fix in v2.9.3 has been released. Please re-open this issue if you experience a crash in `MPSwizzler` with version 2.9.3.

Thanks!

**Comment by genadyo** [comment]
Same crash using 2.9.3?
http://crashes.to/s/0bfb08cf436

**Comment by samgreen** [comment]
@genadyo I am fairly convinced this is an entirely different crash. Your stack trace includes `[MPUIControlBinding execute]` the common theme in stack traces from this thread is a crash in `_postMovedFromSuperview`.

Can you please open a separate issue so we can start tracking down the cause for this?

**Comment by samgreen** [comment]
@genadyo Reviewing the stack trace now

**Comment by samgreen** [comment]
@genadyo Looks to be a similar crash. :(

**Comment by genadyo** [comment]
@samgreen back to work ☺️.

**Comment by sftnhrd** [comment]
@samgreen btw since 2.9.3 we have more MPSwizzler-line-44-crashes.
0.23% vs 0.12% users impacted.

**Comment by samgreen** [comment]
@sftnhrd Interesting, thanks for passing that along.

On our end we're taking a third and fourth look at this issue.

**Comment by kurabi-hc** [comment]
Just started using Mixpanel v2.9.3. Same crash a people have been describing.

**Comment by samgreen** [comment]
Obviously still an issue. Would love any further / different crash reports so we can try and further reproduce the problem.

**Comment by kurabi-hc** [comment]
@samgreen I have 20 crashes so far for just one day. I disabled all events. Still getting crashes though. will mix panel still swizzle methods even if I have ZERO setup via the interactive web tool?

**Comment by lucaseverini** [comment]
Recompile with DISABLE_MIXPANEL_AB_DESIGNER=1 in Preprocessor macros.
I've done this (plus using only events defined via source code) and I never had a crash since then...

**Comment by gavinbunney** [comment]
@kurabi-hc @lucaseverini same here - disabled the AB designer and no more crashes... if you're using cocoapods, just need to add this to your podfile:

```ruby

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    if target.name == "Mixpanel"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DISABLE_MIXPANEL_AB_DESIGNER=1']
      end
    end
  end
end
```

**Comment by genadyo** [comment]
What is that AB designer you all disable?

**Comment by kurabi-hc** [comment]
Thanks @gavinbunney , @lucaseverini

**Comment by thomasjcarey** [comment]
Any word on whether or not this is fixed in 2.9.4? 2.9.3 seems to cache events that were added via the interactive tool months ago, but have since been deleted. Now it's trying to swizzle code that doesn't even exist anymore. At least 20% of our users are experiencing crashes.

**Comment by yarneo** [comment]
Hey guys, we pushed out some new code that helps resolve some of the crashes you have been seeing related to the MPSwizzler issue (#471) . We are working on resolving the rest of the crashes thanks to the feedback and crash logs you guys have been sending.

**Comment by DilyanaTodorova** [comment]
I still see the crash in our crashlogs and we're using 2.9.9

**Comment by yarneo** [comment]
Issue will be fixed in 3.0.0

**Comment by falkobuttler** [comment]
How can we be sure? This issue was claimed to be fixed about 10 times already? Did you find the root cause?

**Comment by yarneo** [comment]
Hi @falkobuttler, thanks for reaching out. 
We did find the root cause. To help us verify the fix we had a few developers (thanks @genadyo) who were experiencing these crashes try it on their app in production and they have confirmed that the crashes are now gone. It is hard for me to tell you that I am 100% sure it is gone, but what I can safely say is that the core issue was found and that the fix has been tested well.

**Comment by falkobuttler** [comment]
That's good news. Thanks for elaborating @yarneo . I look forward to 3.0.0 then

**Comment by kurabi-hc** [comment]
I have the DISABLE_MIXPANEL_AB_DESIGNER=1 and I still get crashes on v2.9.9. I really hope v3.0.0 resolves this.

**Comment by genadyo** [comment]
Happy to help! @falkobuttler

**Comment by samgreen** [comment]
Optimistically marking this thread as resolved with the fixes from v3.0.0

**Comment by genadyo** [comment]
Good job @samgreen & @yarneo

**Comment by jack3010** [comment]
Which versions iOS can run mixpanel 3.0.0? From iOS 7 until iOS 9?

**Comment by jack3010** [comment]
Also, I've downloaded a code from v.3.0.0 the add to my project but New Relic still show crash :(
`EXCEPTION SIGSEGV
LOCATION MPSwizzler.m line 44 in mp_swizzledMethod_2
TIME 06/27, 1:23
Thread 0
libobjc.A.dylib	Show CPU registers objc_release
app9to5	MPSwizzler.m line 44 in mp_swizzledMethod_2
UIKit	[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke]
UIKit	[UIView(Hierarchy) _postMovedFromSuperview:]
UIKit	[UIView(Internal) _addSubview:positioned:relativeTo:]
UIKit	[UIView initWithCoder:]
UIKit	[UIClassSwapper initWithCoder:]
UIKit	UINibDecoderDecodeObjectForValue
UIKit	[UINibDecoder decodeObjectForKey:]
UIKit	[UIRuntimeConnection initWithCoder:]
UIKit	UINibDecoderDecodeObjectForValue
UIKit	UINibDecoderDecodeObjectForValue
UIKit	[UINibDecoder decodeObjectForKey:]
UIKit	[UINib instantiateWithOwner:options:]
UIKit	[UIViewController _loadViewFromNibNamed:bundle:]
UIKit	[UIViewController loadView]
UIKit	[UIViewController loadViewIfRequired]
UIKit	[UINavigationController _layoutViewController:]
UIKit	[UINavigationController _updateScrollViewFromViewController:toViewController:]
UIKit	[UINavigationController _startTransition:fromViewController:toViewController:]
UIKit	[UINavigationController _startDeferredTransitionIfNeeded:]
UIKit	[UINavigationController __viewWillLayoutSubviews]
UIKit	[UILayoutContainerView layoutSubviews]
UIKit	[UIView(CALayerDelegate) layoutSublayersOfLayer:]
QuartzCore	[CALayer layoutSublayers]
QuartzCore	CA::Layer::layout_if_needed(CA::Transaction*
QuartzCore	CA::Layer::layout_and_display_if_needed(CA::Transaction*
QuartzCore	CA::Context::commit_transaction(CA::Transaction*
QuartzCore	CA::Transaction::commit(
QuartzCore	0x1887454bc 0x188744000 + 5308
CoreFoundation	__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
CoreFoundation	__CFRunLoopDoObservers
CoreFoundation	CFRunLoopRunSpecific
UIKit	[UIApplication _run]
UIKit	UIApplicationMain
app9to5	main.m line 15 in main
libdyld.dylib	start `

Someone guys help me to solve that problem. Thanks.

**Comment by yarneo** [comment]
hi @jack3010, by looking at your project specifically on v4.1.3, it seems to be that it is using v2.9.9 which is before the fix. Please move to v3.0.0 and let us know if this persists. If you have any more questions please feel free to contact support@mixpanel.com and not awaken closed threads. Thanks!

**Comment by coolcool1994** [comment]
This bug can be solved very easily. Inside your Xcode workspace, go to Pod File. Then on the left side in the main screen click MixPanel. Go to Build Settings, double click the field of "Preprocessor macros". There you can press + button then write "DISABLE_MIXPANEL_AB_DESIGNER=1". This is all you have to do.

**Comment by yarneo** [comment]
Thanks @coolcool1994 but this has been fixed months ago. Please update to the latest SDK version. Your solution involves disabling A/B testing and that reduces functionality.

**Comment by coolcool1994** [comment]
I got it and I posted solution online THANKS
