### ISSUE TITLE
Mixpanel super property 'Operating System' wrong in iOS 9.1 Beta

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-iphone#343]
It looks like in iOS 9.1 Beta, Apple is switching the return from the below code from 'iPhone OS' to 'iOS'. This has downstream effects as the change will cause reporting by operating system to be broken between these two property values.

Code:
```
NSMutableDictionary *p = [NSMutableDictionary dictionary];
UIDevice *device = [UIDevice currentDevice];
NSLog([device systemName]);
```

Output to NSLog in iOS 9.1:
iOS

As a proposed fix you can assign 'iPhone OS' if the return has 'iOS', but this will not catch users who upgrade to iOS 9.1 but not new versions of the Mixpanel SDK with this fix.

**Comment by samgreen** [comment]
This is resolved on the backend.

**Comment by kohiomobz** [comment]
Hey Guys,

I'm still seeing iOS and iPhone OS properties in Mixpanel.  Can we confirm if this is resolved?

@samgreen @zakj @ryanseams

**Comment by samgreen** [comment]
Hey @kohiomobz thanks for the update. We have only resolved this in the MP trends project. Will be fixed with a backend patch this week.

**Comment by wgins** [comment]
@samgreen Following up, has this been resolved?

**Comment by zetasq** [comment]
+1, this really confuse our alalytics : (

**Comment by mixpanel-travisci** [comment]
This has been resolved on the back end, but will be a few months before we
can deprecate the current functionality.

**Comment by samgreen** [comment]
Interestingly, Apple reverted this change in iOS 10.

We're not going to change the library at this point.

**Comment by yarneo** [comment]
This property is provided by Apple as the current operating system the device is using. This isn't a property that Mixpanel creates and explicitly names.

Please see this article if you want to know more about this and possible workarounds: https://mixpanel.com/help/questions/articles/why-are-iphone-applications-reporting-operating-system-as-either-ios-or-iphone-os
