### ISSUE TITLE
Extension API warnings when installed via Carthage

### ISSUE THREAD

**Issue by JamieWhite** [mixpanel/mixpanel-iphone#394]
I'm using Carthage to add Mixpanel to my project. When do I do this I get xcode warnings "Linking against dylib not safe for use in application extensions: /Users/blah/Mixpanel.framework/Mixpanel"

**Comment by samgreen** [comment]
This is from the [Apple Docs](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html):

> To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes. If you don’t, Xcode reminds you to do so by displaying the warning “linking against dylib not safe for use in application extensions”.

Here's a screenshot to help you find this setting. 
![image](https://cloud.githubusercontent.com/assets/276118/11984395/ad90cfce-a96f-11e5-9153-2e8b0e5a31ed.png)
Please reach out if this doesn't solve your issue!

**Comment by JamieWhite** [comment]
I've done this on my extension target but it will also warn me if a framework I've included has not set this or uses API's not allowed. When I build via carthage i can't pass in any build parameters to cut out the UIApplication.sharedApplication() calls.

Carthage has an update in the works that will allow it to build all schemes in a project and the idea is you should have a separate scheme for main application and extension.

**Comment by samgreen** [comment]
Forgive me if this is obviously wrong, but I'm new to Carthage. Is there any way you could build with `MIXPANEL_APP_EXTENSION` or am I correct that we would need to add a target with this defined to support Carthage (and this is in the future, won't help now)?

If that is true, perhaps a temporary work around would be to edit the Carthage checkout, then run `carthage build` and commit the built framework. Is that helpful?

**Comment by TheDom** [comment]
@samgreen, I think you are correct. Other iOS frameworks are doing the same thing – e.g. https://github.com/ankurp/Dollar.swift/issues/144.

**Comment by samgreen** [comment]
This is resolved with #415

**Comment by poolqf** [comment]
Hi, from what I am seeing, #445 is not fixing the warning. 
Using v2.9.4 and I can still see the `Linking against dylib not safe for use in application extensions...` message
