### ISSUE TITLE
Module not found Mixpanel 3.0.0

### ISSUE THREAD

**Issue by eman8519** [mixpanel/mixpanel-iphone#538]
**Integration Method:** Cocoapods
**Xcode Version:** 7.3.1
**Library Version:** 3.0.0
**Platform:** tvOS
**Language:** Swift

**Description:** 
My project is written in Swift entierly, and I'm using the `use_frameworks!` directive in my `Podfile`. 

After running pod install and then attempting to import the Mixpanel module I receive the error `No such module 'Mixpanel'`

When looking into the issue I also noticed that the folder Pods/Mixpanel only contains two files:
```
LICENSE
README.md
```

**Comment by samgreen** [comment]
Hi @eman8519, that error is actually due to CocoaPods, if you try a clean and rebuild it should resolve itself. We documented this behavior in our [blog post on integrating Swift](https://blog.mixpanel.com/2015/08/17/community-tip-implement-mixpanel-in-swift-apps/).

> Please note that prior to building for the first time, Xcode may display an error: No such module found ‘Mixpanel’. Upon your first successful build this error should disappear and Mixpanel will be integrated within your Swift app!

Does that resolve your issue?

**Comment by eman8519** [comment]
Hi @samgreen thank you for the quick reply. However, that does not solve my problem.  I have investigated further to find that this only seems to impact tvOS builds.  I have a sample project stood up which highlights this issue:

https://github.com/eman8519/mixpanel-cocoapod-issue

**Comment by samgreen** [comment]
@eman8519 Thanks, I'll take a look now.

**Comment by samgreen** [comment]
Ah I see the issue @eman8519, you need to specify the subspec in the podfile. 

    pod 'Mixpanel/tvOS'

It's now building successfully!

**Comment by eman8519** [comment]
Ahh… I completely missed that. Thanks for such a quick turnaround. Closing this issue now.
