### ISSUE TITLE
MIXPANEL_SURVEYS_DEPRECATED adding warnings to project, and Survey is not used

### ISSUE THREAD

**Issue by nickvelloff** [mixpanel/mixpanel-iphone#629]
**Integration Method:** CocoaPods
**Xcode Version:** `Version 8.2.1 (8C1002)`
**Library Version:** `3.08`
**Platform:** iOS
**Language:** Swift main project / Objective-C Mixpanel lib

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** 
```
.../iOS/Pods/Mixpanel/Mixpanel/MPSurveyNavigationController.h:20:27: 'MPSurveyNavigationController' is deprecated: Mixpanel surveys are deprecated as of release 3.0.8

.../iOS/Pods/Mixpanel/Mixpanel/MPSurveyQuestion.h:17:45: 'MPSurveyQuestion' is deprecated: Mixpanel surveys are deprecated as of release 3.0.8

.../iOS/Pods/Mixpanel/Mixpanel/MPSurveyQuestion.h:23:35: 'MPSurveyQuestion' is deprecated: Mixpanel surveys are deprecated as of release 3.0.8

.../iOS/Pods/Mixpanel/Mixpanel/MPSurveyQuestionViewController.h:18:29: 'MPSurveyQuestionViewController' is deprecated: Mixpanel surveys are deprecated as of release 3.0.8
```
**Expected Behavior:** 
That your own code wouldn't produce 4 warnings in my build, when Survey is not used in my project.

**Comment by mbcharbonneau** [comment]
Same problem here. Hope there's a solution for the next release.

**Comment by anlaital** [comment]
same problem here 👍

**Comment by ndonald2** [comment]
Please fix. This is very annoying.

**Comment by pchien** [comment]
This should be fixed by https://github.com/mixpanel/mixpanel-iphone/pull/632 in the next release

**Comment by nickvelloff** [comment]
@pchien thanks!!

**Comment by dstarke** [comment]
I still see a large number of these warnings when building 3.0.9 via Carthage. The warnings are not in my own code, but since I have a build script that executes the Carthage build process, the warnings show up in my build log.

**Comment by pchien** [comment]
@dstarke with survey deprecation we introduced warnings when building our library but I think they shouldn't be visible when building a project that just uses the Mixpanel framework. Do you see the warnings just when Carthage is building Mixpanel or also in your own project?

**Comment by dstarke** [comment]
I only see them when Carthage is building Mixpanel. My project has a build script that runs first that may rebuild all the Carthage libraries we use, and Xcode helpfully includes all warnings that occur in build script phases in the build log. It sounds like this is the behavior you expect.

**Comment by pchien** [comment]
Yeah we decided to have warnings when building Mixpanel so that people who forked the library or manually integrated will get warnings if they use the internal methods for surveys. I'm not sure if there's any way to suppress specifically deprecation warnings for that build phase since Mixpanel will have them for a while.
