### ISSUE TITLE
Crash on -[Mixpanel archiveObject:withFilePath:]  (Mixpanel v3.3.7)

### ISSUE THREAD

**Issue by gilgol** [mixpanel/mixpanel-iphone#818]
**Integration Method:** CocoaPods
**Xcode Version:** 10.1
**Library Version:**  3.3.7
**Platform:** iOS
**Language:** Swift & Objective-C mixed
**Description:**  We're seeing a crash in production after upgrading to 3.3.7 from 3.3.3. 
Currently the crash only happens on iOS 11 (40% - iOS 11.2.6, 10%, iOS 11.4.0) and iOS 12 (40% - iOS 12.1.0,  10% - iOS 12.0.1). 
Also, I can see from the logs that about 30% of all crashes happens while going to or back from background.
Another interesting observation from our logs is that about 60% of the crashes happened while there where some connectivity issues with the device.
As mentioned [here](https://github.com/mixpanel/mixpanel-iphone/issues/816#issuecomment-446184775), we tried to mitigate the issue by reverting back to 3.3.3 which cause a spike in crashes so we've decided to stay with 3.3.7 and try to tackle it somehow differently.

**Expected Behavior:** 
SDK Shuold'nt crash.

**Crash stack trace**
![screen shot 2018-12-12 at 13 24 32](https://user-images.githubusercontent.com/3885164/49866877-a3c07b80-fe11-11e8-99cf-0a41cee92b6b.png)

**Edit**
I looked back at previous issues and found [this one](https://github.com/mixpanel/mixpanel-iphone/issues/795) which might be related? (the stack trace seems similar)

**Comment by leonidgett** [comment]
+1

**Comment by NurLight19** [comment]
I'm facing this problem in version 3.3.7 also.
![mixpanel v3 3 7](https://user-images.githubusercontent.com/20574900/50392157-b28e2300-076d-11e9-8c50-81da7a0c0359.png)

**Comment by gilgol** [comment]
Any news on this? Its been almost two weeks since first reported... This crash became our number 2 crash in production and is getting velocity on its way to be the number 1 crash...

**Comment by zihejia** [comment]
Hi @gilgol , I am really sorry about the delay. We have released v3.3.9 and has a fix for it. Please let me know if there is still any issue and I will reopen it. Thanks!
https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.3.9

**Comment by gilgol** [comment]
Hi @zihejia ,
Thanks for taking the time and trying to solve it.
Unfortunately - the issue is still happening even after upgrading to `v3.3.9`.

This is second biggest crash for our app in production and according to Crashlytics happens 40% of the times on the background (or after coming back from the background)

I'll provide two examples of track trace:
1.
```
Crashed: com.mixpanel.83a4a8f8feed6fb3e0b04e87bcc53335.0x104f17f60
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000001a1b5ccad09

Crashed: com.mixpanel.83a4a8f8feed6fb3e0b04e87bcc53335.0x104f17f60
0  libobjc.A.dylib                0x182b1c908 objc_msgSend + 8
1  Foundation                     0x184301fe4 _encodeObject + 208
2  Foundation                     0x1842a8d0c -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 444
3  Foundation                     0x1843023cc _encodeObject + 1208
4  Foundation                     0x184364ad8 +[NSKeyedArchiver archiveRootObject:toFile:] + 212
5  Mixpanel                       0x1036e4acc -[Mixpanel archiveObject:withFilePath:] + 84
6  Mixpanel                       0x1036e440c -[Mixpanel archiveEvents] + 176
7  Mixpanel                       0x1036e1944 __29-[Mixpanel track:properties:]_block_invoke + 1700
8  libdispatch.dylib              0x183240aa0 _dispatch_call_block_and_release + 24
9  libdispatch.dylib              0x183240a60 _dispatch_client_callout + 16
10 libdispatch.dylib              0x18324a9b4 _dispatch_queue_serial_drain$VARIANT$mp + 608
11 libdispatch.dylib              0x18324b2fc _dispatch_queue_invoke$VARIANT$mp + 336
12 libdispatch.dylib              0x18324bcc8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
13 libdispatch.dylib              0x183254098 _dispatch_workloop_worker_thread$VARIANT$mp + 668
14 libsystem_pthread.dylib        0x183573e70 _pthread_wqthread + 860
15 libsystem_pthread.dylib        0x183573b08 start_wqthread + 4
```

2.
```
com.mixpanel.83a4a8f8feed6fb3e0b04e87bcc53335.0x104f17f60.network
0  libobjc.A.dylib                0x182b1c928 objc_msgSend + 40
1  Foundation                     0x184302068 _encodeObject + 340
2  Foundation                     0x1842a8d0c -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 444
3  Foundation                     0x1842b91e8 -[NSDictionary(NSDictionary) encodeWithCoder:] + 964
4  Foundation                     0x1843023cc _encodeObject + 1208
5  Foundation                     0x1842a8d0c -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 444
6  Foundation                     0x1842b91e8 -[NSDictionary(NSDictionary) encodeWithCoder:] + 964
7  Foundation                     0x1843023cc _encodeObject + 1208
8  Foundation                     0x1842a8d0c -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 444
9  Foundation                     0x1843023cc _encodeObject + 1208
10 Foundation                     0x184364ad8 +[NSKeyedArchiver archiveRootObject:toFile:] + 212
11 Mixpanel                       0x1036e4acc -[Mixpanel archiveObject:withFilePath:] + 84
12 Mixpanel                       0x1036e440c -[Mixpanel archiveEvents] + 176
13 Mixpanel                       0x1036e4314 -[Mixpanel archive] + 28
14 Mixpanel                       0x1036e40c8 __32-[Mixpanel flushWithCompletion:]_block_invoke + 332
15 libdispatch.dylib              0x183240aa0 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x183240a60 _dispatch_client_callout + 16
17 libdispatch.dylib              0x18324a9b4 _dispatch_queue_serial_drain$VARIANT$mp + 608
18 libdispatch.dylib              0x18324b2fc _dispatch_queue_invoke$VARIANT$mp + 336
19 libdispatch.dylib              0x18324bcc8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
20 libdispatch.dylib              0x183254098 _dispatch_workloop_worker_thread$VARIANT$mp + 668
21 libsystem_pthread.dylib        0x183573e70 _pthread_wqthread + 860
22 libsystem_pthread.dylib        0x183573b08 start_wqthread + 4
```

**Comment by mosess** [comment]
Same happens for us
@gilgol do you still experiencing it? have you managed to workaround it?

**Comment by gilgol** [comment]
@mosess unfortunately no. We still experiencing it... we weren't able to reproduce it and its only happens in production (our second biggest crash :( )

Maybe you can also share your insights on the issue with more info such as stack trace and whatever you can find and share. Maybe it will be helpful for @zihejia  to find the issue and fix it.

**Comment by mosess** [comment]
@gilgol @zihejia 
I can try adding some stack traces, but it seems that we've got a workaround for our case - running the mixpanel track on the main thread.
In our use case there was an internal component tracking events - in a different thread.
Running the track on the main thread seems to stop the crashes.
maybe it could also help for identifying the issue.

**Comment by zihejia** [comment]
Hi @gilgol @mosess @NurLight19 We have released 3.4.8 which contains a fix for this issue. Please try it out. 
https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.4.8

I'm closing this issue for now, please feel free to reopen it if the problem still exists.
